import type { Metadata } from "next";

import Analytics from "~/components/Analytics";
import "./globals.css";
import { cn } from "~/utils/cn";
import { ThemeProvider } from "~/app/providers";
import { inter } from "~/utils/fontts";

export const metadata: Metadata = {
  title: "Boot Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "antialiased common-bg")}>
        <ThemeProvider attribute="class" enableSystem={false}>
          {children}
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
